# Generated by Django 5.2.10 on 2026-04-12 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_message', models.TextField()),
                ('sender_number', models.CharField(max_length=20)),
                ('error_message', models.TextField()),
                ('is_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaultReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_code', models.CharField(choices=[('PUMP', 'Pump Failure'), ('LEAK', 'Pipe Leak'), ('DRY', 'Borehole Dry'), ('CONTAM', 'Contamination'), ('VANDAL', 'Vandalism'), ('OTHER', 'Other')], max_length=10)),
                ('sender_number', models.CharField(max_length=20)),
                ('ticket_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('water_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='gateway.waterpoint')),
            ],
        ),
    ]
